### PR TITLE
Refactored DepCleanMojo

### PR DESCRIPTION
**Pull request by ABHAY0O7**
- Removed unused import.
- Removed unused fields.
- Removed unused or never thrown Exception.
- Fix typos.
- Make searching faster while using configuration `ignoredependencies`.

### CODE REVIEW

**Comment by cesarsotovalero** [comment]
Hi @ABHAY0O7, thanks for this proposal. 
Can you add some unit tests along with this PR?

**Comment by ABHAY0O7** [comment]
> Hi @ABHAY0O7, thanks for this proposal.
> Can you add some unit tests along with this PR?

Hi @cesarsotovalero 
I was trying to add a unit test but I faced some problems that I mentioned here #86.
Please help me with this issue, so that I can continue my work.

**Comment by ABHAY0O7** [comment]
Hi @cesarsotovalero 
I added an IT for depCleanMojo.
But I don't know how to pass these two failing checks.
Also, I am unable to understand the report generated by these two checks. :sweat_smile:
So, can you please suggest to me, what can I do to pass these checks?

**Comment by ABHAY0O7** [comment]
fixes #86

**Comment by cesarsotovalero** [comment]
> Hi @cesarsotovalero
> I added an IT for depCleanMojo.
> But I don't know how to pass these two failing checks.
> Also, I am unable to understand the report generated by these two checks. 😅
> So, can you please suggest to me what can I do to pass these checks?

Hi @ABHAY0O7,
SonarCloud checks for potential bugs and code smells using static analysis. You can see the report [here](https://sonarcloud.io/dashboard?id=castor-software_depclean) (notice that these metrics are mostly related to maintainability, so a PR will not be rejected because of not passing this gate). On the other hand, the Codecov report indicates how the PR affects the code coverage of the project, as measured by the unit tests. To not lower down the coverage, it is a good practice to always add unit tests on every PR that you make.

**Comment by ABHAY0O7** [comment]
Hey! @cesarsotovalero I have completed the work.
Now you can review the whole PR.

Thank you.

**Review by cesarsotovalero — APPROVED** [review]

**Comment by cesarsotovalero** [comment]
Hi @ABHAY0O7, LGTM. Notice that I fixed all the checks before merging. Thanks for your contribution, and keep going!

**Pull request merged**
