### PR TITLE
End2end tests for core

### PR DESCRIPTION
**Pull request by afillatre**
Coverage could still be higher, but this should make new features way more easy to test

### CODE REVIEW

**Comment by cesarsotovalero** [comment]
Hi @afillatre, 

Thanks a lot for submitting these improvements.

Can you please resolve the conflicts with the master branch so I can merge it 😄

FYI: I added an extra layer of static analysis checks based on the analysis of imports in source files. This means that DepClean now also checks for usages in the source code of the project, which removes false positives such as [lombok](https://projectlombok.org/) and [sl4j](https://www.slf4j.org/), see https://github.com/castor-software/depclean/pull/126

**Comment by afillatre** [comment]
@cesarsotovalero that's done. `DefaultCallGraphTest` may fail on certain condition, because it tests a class using static members, so either this should be refactored to not be static (best solution IMAO) or any test that calls the `DefaultCallGraph` should reset it after each method.

**Comment by afillatre** [comment]
Although, looking at the Gradle project, I updated the methods that get the output folders to get a set of folders. I did not do that refactoring to your new code though. This is not blocking, but may need to be done later.

**Comment by cesarsotovalero** [comment]
> @cesarsotovalero that's done. `DefaultCallGraphTest` may fail on certain condition, because it tests a class using static members, so either this should be refactored to not be static (best solution IMAO) or any test that calls the `DefaultCallGraph` should reset it after each method.

I agree, `DefaultCallGraph` should not be a static class. Some refactoring of this class is needed.

**Pull request merged**
